
server:
  port: 80
  servlet:
    context-path: /


spring:
  datasource:
    #mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.4.26.45:3306/bp_demo?serverTimezone=GMT%2b8&useSSL=false&Unicode=true&characterEncoding=utf8&autoReconnectForPools=true&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: root_Zhang@2022.cn
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    devtools:
    restart:
      exclude: static/**,public/**
  freemarker:
    cache: false
    suffix: .ftl
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/


swagger:
  production: false
  basic:
    enable: true
    username: small-rose
    password: Small@2022

logging:
  level:
    root: info
    org:
      springframework:
        transaction: info
        orm: info
      hibernate: info