package cn.xiaocai.demo.kingbase.web.mapper.mysql;

import cn.xiaocai.demo.kingbase.web.model.mysql.MysqlAccount;
import java.util.List;

public interface MysqlAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Thu Feb 24 14:14:50 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Thu Feb 24 14:14:50 CST 2022
     */
    int insert(MysqlAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Thu Feb 24 14:14:50 CST 2022
     */
    MysqlAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Thu Feb 24 14:14:50 CST 2022
     */
    List<MysqlAccount> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Thu Feb 24 14:14:50 CST 2022
     */
    int updateByPrimaryKey(MysqlAccount record);
}