package cn.xiaocai.demo.kingbase.web.mapper.mysql;

import cn.xiaocai.demo.kingbase.web.model.mysql.MysqlOrder;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MysqlOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Feb 24 14:14:50 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Feb 24 14:14:50 CST 2022
     */
    int insert(MysqlOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Feb 24 14:14:50 CST 2022
     */
    MysqlOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Feb 24 14:14:50 CST 2022
     */
    List<MysqlOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Feb 24 14:14:50 CST 2022
     */
    int updateByPrimaryKey(MysqlOrder record);
}