server:
  port: 31006
  servlet:
    context-path: /

# DataSourceConfig
#spring:
#  application:
#    name: demo-admin
#  datasource:
#    dbType: oracle
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#    filters: stat,wall,log4j
#    initialSize: 5
#    maxActive: 100
#    maxPoolPreparedStatementPerConnectionSize: 20
#    maxWait: 60000
#    minEvictableIdleTimeMillis: 300000
#    minIdle: 5
#    poolPreparedStatements: true
#    testOnBorrow: false
#    testOnReturn: false
#    testWhileIdle: true
#    timeBetweenEvictionRunsMillis: 60000
#    validationQuery: SELECT 'x' FROM DUAL
#    #url: jdbc:oceanbase://29.30.194.204:2883/autocv?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&allowMultiQueries=true
#    #username: autocv@property_pt22cvm_autocv_dev#cx_x86_obdev:1649233511
#    #password: Ce_Sh1%Pa2s_obdb
#    obtype: com.alibaba.druid.pool.DruidDataSource
#    oburl: jdbc:oceanbase://29.30.130.208:2883/amsdb01?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&allowMultiQueries=true
#    obusername: AMSDB01@amsdb01#cx_xc_obcluster
#    obpassword: '@5EDcft%7'
#    obdriver-class-name: com.oceanbase.jdbc.Driver
#    obuse: true
#    useGlobalDataSourceStat: true
#    #druid:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@29.28.144.215:18215:amsdb
#    username: Ams
#    password: 'Kjhs%3162TB6ljp'


spring:
  application:
    name: demo-admin
  #1.JDBC数据源
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    druid:
      oceanbase03:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:oceanbase:oracle://your_ip:2883/amsdb03  #?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&allowMultiQueries=true
        username: 'AMSDB03@amsdb03#cx_xc_obcluster'
        password: '@5IDcft%8'
        driver-class-name: com.oceanbase.jdbc.Driver
      oceanbase:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:oceanbase:oracle://your_ip:2883/amsdb01  #?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&allowMultiQueries=true
        username: 'AMSDB01@amsdb01#cx_xc_obcluster'
        password: '@5EDcft%7'
        driver-class-name: com.oceanbase.jdbc.Driver
        #初始化连接池的连接数量 大小，最小，最大
        #        initial-size: 5
        #        min-idle: 5
        #        max-active: 20
        #        #配置获取连接等待超时的时间
        #        max-wait: 60000
        #        #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        #        time-between-eviction-runs-millis: 60000
        #        # 配置一个连接在池中最小生存的时间，单位是毫秒
        #        min-evictable-idle-time-millis: 30000
        #        # 配置一个连接在池中最大生存的时间，单位是毫秒
        #        max-evictable-idle-time-millis: 300000
        testWhileIdle: false
        validationQuery: SELECT 1
      #        validationQuery: SELECT 1 FROM dual
      #        test-on-borrow: true
      #        test-on-return: false
      #        # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      #        pool-prepared-statements: true
      #        max-pool-prepared-statement-per-connection-size: 20
      #        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #        filters: stat,wall,slf4j
      #        filter:
      #          stat:
      #            merge-sql: true
      #            slow-sql-millis: 5000

      oracle:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@your_ip:18215:amsdb
        username: Ams
        password: Kjhs%3162TB6ljp
        #初始化连接池的连接数量 大小，最小，最大
        #        initial-size: 5
        #        min-idle: 5
        #        max-active: 20
        #        #配置获取连接等待超时的时间
        #        max-wait: 60000
        #        #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        #        time-between-eviction-runs-millis: 60000
        #        # 配置一个连接在池中最小生存的时间，单位是毫秒
        #        min-evictable-idle-time-millis: 30000
        #        # 配置一个连接在池中最大生存的时间，单位是毫秒
        #        max-evictable-idle-time-millis: 300000
        testWhileIdle: false
        validationQuery: SELECT 1
#        validationQuery: SELECT 1 FROM dual
#        test-on-borrow: true
#        test-on-return: false
#        # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
#        pool-prepared-statements: true
#        max-pool-prepared-statement-per-connection-size: 20
#        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#        filters: stat,wall,slf4j
#        filter:
#          stat:
#            merge-sql: true
#            slow-sql-millis: 5000
logging:
  level:
    com.cppic.obgenerator.small: debug


