server:
  port: 8802
  servlet:
    context-path: /bp-demo



spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bp-demo?serverTimezone=GMT%2b8&useSSL=false&Unicode=true&characterEncoding=utf8&autoReconnectForPools=true&allowMultiQueries=true&rewriteBatchedStatements=true
      username: root
      password: 123456
    kingbase:
      driver-class-name: com.kingbase8.Driver
      url: jdbc:kingbase8://192.168.10.191:54321/bp_dev?serverTimezone=GMT%2b8&useSSL=false&Unicode=true&characterEncoding=utf8&autoReconnectForPools=true&allowMultiQueries=true&rewriteBatchedStatements=true
      username: bpdev01
      password: bpdev0123


logging:
  level:
    root: info
    cn.xiaocai.demo.kingbase.web.mapper: debug   # 这里可以关闭SQL打印
    org.springframework.data.mongodb.core: info
    org:
      springframework:
        transaction: DEBUG
        orm: DEBUG
      apache:
        ibatis: DEBUG
    druid:
      sql:
        DataSource: DEBUG
        Connection: DEBUG
        Statement: DEBUG
        #ResultSet: DEBUG
    com:
      fndsoft:
        boot:
          platform: ERROR
      fenet:
        insurance:
          core:
            datasource: DEBUG
    springfox:
      documentation: error