server:
  port: 8802
  servlet:
    context-path: /bp-demo



spring:
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bp-demo?serverTimezone=GMT%2b8&useSSL=false&Unicode=true&characterEncoding=utf8&autoReconnectForPools=true&allowMultiQueries=true&rewriteBatchedStatements=true
      username: root
      password: 123456
    kingbase:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.kingbase8.driver
      url: jdbc:kingbase8://localhost:3306/bp-demo?serverTimezone=GMT%2b8&useSSL=false&Unicode=true&characterEncoding=utf8&autoReconnectForPools=true&allowMultiQueries=true&rewriteBatchedStatements=true
      username: root
      password: 123456