server:
  port: 8080
  servlet:
    context-path: /druid-dynamic
    session:
      timeout: 30m

# 数据源配置

spring:
  autoconfigure:
    # \u6392\u9664 Druid \u81EA\u52A8\u914D\u7F6E
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:

    # \u6307\u5B9A\u4F7F\u7528 Druid \u6570\u636E\u6E90
    type: com.alibaba.druid.pool.DruidDataSource
    # \u52A8\u6001\u6570\u636E\u6E90\u6587\u6863 https://www.kancloud.cn/tracy5546/dynamic-datasource/content
    dynamic:
      #\u8BBE\u7F6E\u9ED8\u8BA4\u7684\u6570\u636E\u6E90\u6216\u8005\u6570\u636E\u6E90\u7EC4,\u9ED8\u8BA4\u503C\u5373\u4E3A master
      primary: master
      datasource:
      # \u4E3B\u5E93\u6570\u636E\u6E90
        master:
           url: jdbc:mysql://localhost:3306/bp_demo?serverTimezone=GMT%2b8&useSSL=false&Unicode=true&characterEncoding=utf8&autoReconnectForPools=true&allowMultiQueries=true&rewriteBatchedStatements=true
           username: root
           password: 123456
        slave:
            enable: false
            driverClassName: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/bp_demo?serverTimezone=GMT%2b8&useSSL=false&Unicode=true&characterEncoding=utf8&autoReconnectForPools=true&allowMultiQueries=true&rewriteBatchedStatements=true
            username: root
            password: 123456
        bpjyopr:
            enable: false
            driverClassName: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/bp_demo?serverTimezone=GMT%2b8&useSSL=false&Unicode=true&characterEncoding=utf8&autoReconnectForPools=true&allowMultiQueries=true&rewriteBatchedStatements=true
            username: root
            password: 123456
        bptzopr:
            enable: false
            driverClassName: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/bp_demo?serverTimezone=GMT%2b8&useSSL=false&Unicode=true&characterEncoding=utf8&autoReconnectForPools=true&allowMultiQueries=true&rewriteBatchedStatements=true
            username: root
            password: 123456
        bpdzopr:
            enable: false
            driverClassName: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/bp_demo?serverTimezone=GMT%2b8&useSSL=false&Unicode=true&characterEncoding=utf8&autoReconnectForPools=true&allowMultiQueries=true&rewriteBatchedStatements=true
            username: root
            password: 123456
        druid:
          # \u521D\u59CB\u8FDE\u63A5\u6570
          initialSize: 5
          # \u6700\u5C0F\u8FDE\u63A5\u6C60\u6570\u91CF
          minIdle: 10
          # \u6700\u5927\u8FDE\u63A5\u6C60\u6570\u91CF
          maxActive: 20
          # \u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4
          maxWait: 60000
          # \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
          timeBetweenEvictionRunsMillis: 60000
          # \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
          minEvictableIdleTimeMillis: 300000
          # \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5927\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
          maxEvictableIdleTimeMillis: 900000
          # \u914D\u7F6E\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548
          validationQuery: SELECT 1 FROM DUAL
