server:
  port: 8088
  servlet:
    context-path: /db-qartz



spring:
  datasource:
    quartz:
      #driver-class-name: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_quartz?serverTimezone=GMT%2B8
      username: root
      password: 123456
  quartz:
    job-store-type: jdbc # \u4F7F\u7528\u6570\u636E\u5E93\u5B58\u50A8
    scheduler-name: hyhScheduler # \u76F8\u540C Scheduler \u540D\u5B57\u7684\u8282\u70B9\uFF0C\u5F62\u6210\u4E00\u4E2A Quartz \u96C6\u7FA4
    wait-for-jobs-to-complete-on-shutdown: true # \u5E94\u7528\u5173\u95ED\u65F6\uFF0C\u662F\u5426\u7B49\u5F85\u5B9A\u65F6\u4EFB\u52A1\u6267\u884C\u5B8C\u6210\u3002\u9ED8\u8BA4\u4E3A false \uFF0C\u5EFA\u8BAE\u8BBE\u7F6E\u4E3A true
    jdbc:
      initialize-schema: never # \u662F\u5426\u81EA\u52A8\u4F7F\u7528 SQL \u521D\u59CB\u5316 Quartz \u8868\u7ED3\u6784\u3002\u8FD9\u91CC\u8BBE\u7F6E\u6210 never \uFF0C\u6211\u4EEC\u624B\u52A8\u521B\u5EFA\u8868\u7ED3\u6784\u3002
    properties:
      org:
        quartz:
          # JobStore \u76F8\u5173\u914D\u7F6E
          jobStore:
            dataSource: quartzDataSource # \u4F7F\u7528\u7684\u6570\u636E\u6E90
            class: org.quartz.impl.jdbcjobstore.JobStoreTX # JobStore \u5B9E\u73B0\u7C7B
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_ # Quartz \u8868\u524D\u7F00
            isClustered: true # \u662F\u96C6\u7FA4\u6A21\u5F0F
            clusterCheckinInterval: 1000
            useProperties: false
          # \u7EBF\u7A0B\u6C60\u76F8\u5173\u914D\u7F6E
          threadPool:
            threadCount: 25 # \u7EBF\u7A0B\u6C60\u5927\u5C0F\u3002\u9ED8\u8BA4\u4E3A 10 \u3002
            threadPriority: 5 # \u7EBF\u7A0B\u4F18\u5148\u7EA7
            class: org.quartz.simpl.SimpleThreadPool # \u7EBF\u7A0B\u6C60\u7C7B\u578B

