package com.xiaocai.demo.mutilds.mapper.kingbase;

import com.xiaocai.demo.mutilds.model.kingbase.KbOrder;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface KbOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Mar 10 18:06:53 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Mar 10 18:06:53 CST 2022
     */
    int insert(KbOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Mar 10 18:06:53 CST 2022
     */
    KbOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Mar 10 18:06:53 CST 2022
     */
    List<KbOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Thu Mar 10 18:06:53 CST 2022
     */
    int updateByPrimaryKey(KbOrder record);
}