
server:
  port: 8806
  servlet:
    context-path: /db-quartz

spring:
  # Quartz \u7684\u914D\u7F6E\uFF0C\u5BF9\u5E94 QuartzProperties \u914D\u7F6E\u7C7B  for com.xiaocai.demo.quartz.jobs \u6F14\u793A\u4EFB\u52A1\u7684\u914D\u7F6E\u65B9\u5F0F
  quartz:
    job-store-type: memory # Job \u5B58\u50A8\u5668\u7C7B\u578B\u3002\u9ED8\u8BA4\u4E3A memory \u8868\u793A\u5185\u5B58\uFF0C\u53EF\u9009 jdbc \u4F7F\u7528\u6570\u636E\u5E93\u3002
    auto-startup: true # Quartz \u662F\u5426\u81EA\u52A8\u542F\u52A8
    startup-delay: 0 # \u5EF6\u8FDF N \u79D2\u542F\u52A8
    wait-for-jobs-to-complete-on-shutdown: true # \u5E94\u7528\u5173\u95ED\u65F6\uFF0C\u662F\u5426\u7B49\u5F85\u5B9A\u65F6\u4EFB\u52A1\u6267\u884C\u5B8C\u6210\u3002\u9ED8\u8BA4\u4E3A false \uFF0C\u5EFA\u8BAE\u8BBE\u7F6E\u4E3A true
    overwrite-existing-jobs: false # \u662F\u5426\u8986\u76D6\u5DF2\u6709 Job \u7684\u914D\u7F6E
    properties: # \u6DFB\u52A0 Quartz Scheduler \u9644\u52A0\u5C5E\u6027
      org:
        quartz:
          threadPool:
            threadCount: 25 # \u7EBF\u7A0B\u6C60\u5927\u5C0F\u3002\u9ED8\u8BA4\u4E3A 10 \u3002
            threadPriority: 5 # \u7EBF\u7A0B\u4F18\u5148\u7EA7
            class: org.quartz.simpl.SimpleThreadPool # \u7EBF\u7A0B\u6C60\u7C7B\u578B
  #    jdbc: # \u8FD9\u91CC\u6682\u65F6\u4E0D\u8BF4\u660E\uFF0C\u4F7F\u7528 JDBC \u7684 JobStore \u7684\u65F6\u5019\uFF0C\u624D\u9700\u8981\u914D\u7F6E

  # DataSource Config for tasks  com.xiaocai.demo.quartz.tasks \u81EA\u5DF1\u5B9A\u4E49\u4E00\u5F20\u4EFB\u52A1\u8868\u7BA1\u7406\u4EFB\u52A1\u7684\u793A\u4F8B
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_quartz?serverTimezone=GMT%2b8&useSSL=false&Unicode=true&characterEncoding=utf8&autoReconnectForPools=true&allowMultiQueries=true&rewriteBatchedStatements=true

  # jpa \u914D\u7F6E
  jpa:
    #\u5728\u5EFA\u8868\u7684\u65F6\u5019\uFF0C\u5C06\u9ED8\u8BA4\u7684\u5B58\u50A8\u5F15\u64CE\u5207\u6362\u4E3A InnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # \u914D\u7F6E\u5728\u65E5\u5FD7\u4E2D\u6253\u5370\u51FA\u6267\u884C\u7684 SQL \u8BED\u53E5\u4FE1\u606F\u3002
    show-sql: true
    # \u914D\u7F6E\u6307\u660E\u5728\u7A0B\u5E8F\u542F\u52A8\u7684\u65F6\u5019\u8981\u5220\u9664\u5E76\u4E14\u521B\u5EFA\u5B9E\u4F53\u7C7B\u5BF9\u5E94\u7684\u8868\u3002
    hibernate:
      ddl-auto: update #create #update



  thymeleaf:
    #\u6A21\u677F\u7684\u6A21\u5F0F\uFF0C\u652F\u6301 HTML, XML TEXT JAVASCRIPT
    mode: HTML
    #\u7F16\u7801 \u53EF\u4E0D\u7528\u914D\u7F6E
    encoding: UTF-8
    #\u5185\u5BB9\u7C7B\u522B,\u53EF\u4E0D\u7528\u914D\u7F6E
    servlet:
      content-type: text/html
    #\u5F00\u53D1\u914D\u7F6E\u4E3Afalse,\u907F\u514D\u4FEE\u6539\u6A21\u677F\u8FD8\u8981\u91CD\u542F\u670D\u52A1\u5668
    cache: false
    #\u914D\u7F6E\u6A21\u677F\u8DEF\u5F84\uFF0C\u9ED8\u8BA4\u662Ftemplates\uFF0C\u53EF\u4EE5\u4E0D\u7528\u914D\u7F6E
    prefix: classpath:/templates/
    suffix: .html

#  freemarker:
#    templateLoaderPath: classpath:/templates/
#    suffix: .ftl
#    charset: UTF-8
#    content-type: text/html
#    expose-request-attributes: true
#    expose-session-attributes: true
#    request-context-attribute: request
#    settings:
#      number_format: 0.##########
    #cache: false


##   ##  ##  ##  ##  ##
#  \u89E3\u6790\uFF1A
#  ddl-auto\u8868\u793A\u5BF9\u6570\u636E\u5E93\u8FDB\u884C\u81EA\u52A8\u5316\u914D\u7F6E
#     \u503C\u6709\u4E09\u4E2A\u9009\u62E9\uFF1A
#     create\u8868\u793A\u521B\u5EFA\uFF0C\u5982\u679C\u8BF4\u6570\u636E\u5E93\u4E2D\u4E0D\u7BA1\u6709\u6CA1\u6709\u8FD9\u5F20\u8868\uFF0C\u90FD\u4F1A\u5148\u5E72\u6389\uFF0C\u7136\u540E\u5728\u91CD\u65B0\u521B\u5EFA\uFF0C\u4E0D\u9002\u5408\u751F\u4EA7\u73AF\u5883
#     update\u8868\u793A\u66F4\u65B0\uFF0C\u5982\u679C\u8BF4\u6570\u636E\u5E93\u4E2D\u6709\u8FD9\u5F20\u8868\uFF0C\u5219\u6267\u884C\u8FDB\u884C\u66F4\u65B0\u8868\u4E2D\u7684\u6570\u636E\uFF0C\u5982\u679C\u6CA1\u6709\u8FD9\u5F20\u8868\uFF0C\u5219\u76F4\u63A5\u521B\u5EFA\u8FD9\u5F20\u8868\uFF0C\u9002\u5408\u751F\u4EA7\u73AF\u5883
#     none \u6CA1\u6709\u4EFB\u4F55\u64CD\u4F5C
#    https://blog.csdn.net/cmx1060220219/article/details/106259423
#



#mybatis-plus\u914D\u7F6E
#mybatis-plus:
#  global-config:
#    db-config:
#      field-strategy: not_empty
#      id-type: auto
#      db-type: mysql
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#    banner: false
#  mapper-locations: classpath:/mapper/*Mapper.xml


### freemarker
#  spring.freemarker.templateLoaderPath=classpath:/templates/
#  spring.freemarker.suffix=.ftl
#  spring.freemarker.charset=UTF-8
#  spring.freemarker.request-context-attribute=request
#  spring.freemarker.settings.number_format=0.##########