server:
  port: 9090
  servlet:
    context-path: /qrCode



spring:
  mvc:
    view:
      prefix: /
      suffix: .html




alipay:
  alipay_accredit_url: https://openauth.alipay.com/oauth2/appToAppAuth.htm?
  app_id: 2014042100005160
  alipay_redirect_uri: https://plytst.e-acic.com/bp-payonline/accredit.do
  alipayuser_accredit_url: 10
  # #private key
  alipay_private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCD3/FdPjPBMo2p3Ee7Qq3ho9Z1MUcBbH96Gau78xwVUZe+1xIoPcubMuGVVqHh2LaOzTs6Y9qLxs5oSV8DAsmyAYBp08ePRyAHBrFhzx+vlpao4W+sYrjDGhMegOI0NNlIc/VIp68aOORYMI9RJJzBg74kaJ+8otVwsIz+wV59hUFk8Y6AqOnkyLe8CHe984eD5dOe4Kp/HJDCi5GbK1AauaJhMkET1/AAMJvD3VF3MASpxY6f1wy5QD4CJ/2kG8sF9xfx67+md+shwEdp9Ut2YGBYhY8EqAkedt4K3mczDTD94k/bH/zXc7vEY/heARmW3sxrATtGhvaChszuVY5RAgMBAAECggEAP7Rv2ZZR1BOCwbqK4Fg+vVCzKdvLLFHoZuh9wIaZW2cWAffNaqkncWqr9MNr4jkZP3S/Ft7j1UANt+0xu7eeDaKSEQ1gSsOWIi7Gg7RV3zHEyAJXOxRZos42zDaAj620BT8XD6kJeoZfMIcMxKsGGql0sgvklnCm4RA4nFx3M/TzFWB9xUbpvrqdQ5uZLWoNLKDg+QB0ibyzceiTD9K180MMRMdRg1p3JHgZIRLJYcUGWLe89hzbkH09zgG2XwrTBK8DA5itQt8Gu17jzl6kUu3Lvaeyyw30buEN1RoAriALZu906InVWH+TJbFugOGeUMNcaXD+h1Msf1zaInElPQKBgQDtc/Zd3LWbt7ixSnfshqO8PZ626imU6WUmwGi5Xvr6I+Zr7xkQtpfjcCnHb1ppuHlN4ajvHKF6lqRS2M1ZWaZJr2cQlpkv9OPagGw+3c/u3CWxWK3KM6c8INukyJQab4H3grIX2EPQmL0aamoPD571Ep4R+rIcWBWdbVlpO9UTUwKBgQCOLN7teoT6PpcrWuypxgnu0NmauMNMU55BrX1tGSc9ne8OoXyW/x6JNh9qJCP8cvvE2Ho/UhhoGblTW58g6KWqfAqwtWFy95gcezaO0PB/MMKnue0g/Aw/L1MCKJXsaHSUOW7Kc6PSPkTxDf5wIeZ+1gXV1hQLJFj6StWT5YPnSwKBgE8XMfdfnWoJjs4WtM0mp4D6sVPRuRnth5CZxAgCd+w7avOGhz3G496QrInOMDpIhLcJM+C5E5wmcwNZTUS2lKm0b8rZrpqHoiFUZzmlXi38S92/YNuZytk/RImleZc4jvynHrTMhwIC7fHPghYUKOkOU3I/o3XHbSOrmX1wvW8bAoGAVpUe4dKWPut1FjMWI0H2dJh9nIrebJITs32a/6Cs1AplNizD+hS9nOP396SwwaGoj7UhpYQyVtsrkIcgfmMP2KYXwIuFIAWGffnPPOQjQeII+SnyLf8w2h3Q2GStAL6QGGBthx8rafL/+ykBhXovq5hdD1+C71IgWbTPInVIgccCgYBW285F4cZAoj5JaBIRqUb7WLKxlMftBL3uCeLePsEGevAXXJAzXBoEqO7ZWebQMItXvnWwlM7OkzDFI9Jg2VL7W1MAdrxyE8NgUuzHfugkHqw87zT1nP9AM3h2PtKTa/hou69Q2LVoctuGnmqwdZmfYC3yBPzZz5JvT9o33yYTcA==
  # public key
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxuFysm3sX7U1vA7eHKvXiknELhgqRZ4qx+K/hfLWZDo13lQMPUBNVKkKtcAJ4ag7Bws6DoF311UDnwRhgcU179pUbW8KjpB7LbbWySplUOzXJnR3OWz3iB9n5Q0RBR/ds33beWAkGePim9LDkbI+JDyd3flSedvnShwFUXJx2pthUrhKbzX3T0C3HqcwLhoqix3Z8yhE3x+IpkvJCg6+O5JN/DyAsB2TlYT9h19qSS48+EIqjCj7tckx0o4zGajgqnAOwxs6gYDN0um7DUR2SH2uHaGn10Wz9fq6Xp8ZIjgaShQ/WZ+JtHdRBE+PevmEjRXwd1CNVCSXmBQwwnicuwIDAQAB