
server:
  port: 8090
  servlet:
    context-path:  /bp-web
    session:
      timeout: 3600

system-conf:
  dao: mysql   # mapper \u5BF9\u5E94\u4E0D\u540C\u6570\u636E\u5E93xml\u6587\u4EF6\u5939\u540D\u79F0\uFF0Cmysql \u3001oracle \u3001kingBase


logging:
  level:
    root: info
    com.xiaocai.mybatis.test.module.mapper: debug   # \u8FD9\u91CC\u53EF\u4EE5\u5173\u95EDSQL\u6253\u5370
    org.springframework.data.mongodb.core: info
    org:
      springframework:
        transaction: DEBUG
        orm: DEBUG
      apache:
        ibatis: DEBUG
    druid:
      sql:
        DataSource: DEBUG
        Connection: DEBUG
        Statement: DEBUG
        #ResultSet: DEBUG
    com:
      fndsoft:
        boot:
          platform: ERROR
      fenet:
        insurance:
          core:
            datasource: DEBUG
    springfox:
      documentation: error

spring:
  servlet:
    multipart:
      enabled: true
      maxFileSize: 20MB
      maxRequestSize: 100MB
  application:
    name: BPWebServer
  redis:
    timeout: 1000
    port: 6379
    host: 192.168.10.187
    password: bcis
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  mvc:
    view:
      prefix: /  #/WEB-INF/jsp/
      suffix: .jsp
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #\u6307\u5B9A\u65F6\u95F4\u683C\u5F0F
    time-zone: GMT+8

  datasource:
    name: bpDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      master:
        url: jdbc:mysql://192.168.10.191:3306/bp_dev_0217?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
        username: sf_dev_01
        password: Sf@123321
      slave:
        driver-class-name: com.kingbase8.Driver
        enable: true  # \u542F\u52A8\u5F00\u5173\uFF0C\u540C\u65F6\u8981\u6FC0\u6D3B DataSourceConfiguration \u76F8\u5173\u7684\u914D\u7F6E
        url: jdbc:kingbase8://192.168.10.191:54321/bp_dev?serverTimezone=GMT%2b8&useSSL=false&Unicode=true&characterEncoding=utf8&autoReconnectForPools=true&allowMultiQueries=true&rewriteBatchedStatements=true
        username: bpdev01
        password: bpdev0123
      bpjyopr:
        enable: false
        url: jdbc:mysql://192.168.10.191:3306/bp_dev_0217?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
        username: sf_dev_01
        password: Sf@123321
      bptzopr:
        enable: false
        url: jdbc:mysql://192.168.10.191:3306/bp_dev_0217?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
        username: sf_dev_01
        password: Sf@123321
      bpdzopr:
        enable: false
        url: jdbc:mysql://192.168.10.191:3306/bp_dev_0217?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
        username: sf_dev_01
        password: Sf@123321

      initialSize: 5  # \u521D\u59CB\u5316\u5927\u5C0F
      minIdle: 5  # \u6700\u5C0F\u8FDE\u63A5\u6570
      maxActive: 100 # \u6700\u5927\u8FDE\u63A5\u6570
      maxWait: 60000 # \u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4
      timeBetweenEvictionRunsMillis: 60000 # \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
      minEvictableIdleTimeMillis: 300000  # \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
      maxEvictableIdleTimeMillis: 900000  # \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5927\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
      validationQuery: SELECT 1 FROM DUAL #\u9A8C\u8BC1\u8FDE\u63A5\u662F\u5426\u6709\u6548\u7684sql
      testWhileIdle: true
      testOnBorrow: false #\u83B7\u53D6\u8FDE\u63A5\u65F6\u5148\u9A8C\u8BC1\u8FDE\u63A5\u662F\u5426\u6709\u6548
      testOnReturn: false #\u5F52\u8FD8\u8FDE\u63A5\u65F6\u5148\u9A8C\u8BC1\u8FDE\u63A5\u662F\u5426\u6709\u6548
      poolPreparedStatements: true # \u6253\u5F00PSCache\uFF0C\u5E76\u4E14\u6307\u5B9A\u6BCF\u4E2A\u8FDE\u63A5\u4E0APSCache\u7684\u5927\u5C0F
      maxPoolPreparedStatementPerConnectionSize: 20 # \u6253\u5F00PSCache\uFF0C\u5E76\u4E14\u6307\u5B9A\u6BCF\u4E2A\u8FDE\u63A5\u4E0APSCache\u7684\u5927\u5C0F
      filters: config,stat,slf4j  # \u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters\uFF0C\u53BB\u6389\u540E\u76D1\u63A7\u754C\u9762sql\u65E0\u6CD5\u7EDF\u8BA1\uFF0C'wall'\u7528\u4E8E\u9632\u706B\u5899
      decrypt: #\u81EA\u5B9A\u4E49\u7684\u914D\u7F6E\u6587\u4EF6 druid \u89E3\u5BC6\u5BC6\u7801\u4F7F\u7528\u7684\u516C\u94A5
        publickey: "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKLq631Q7G0ojRaUklMbdXvR2PbV7Z058DahC8G48J7jnq5AzaW60VZHo2SgpjhsMrwk7VrVWg6TRkZT3KlKp6MCAwEAAQ=="
        password: "HrXNxnKcwYPXVBTf3gtW2dB1VEt9o2YKZzWlykb9pH7TfrjjgoWKdsxFM9czLp79F2+bTfWO2givtdI+lJ6N3A=="
      connectionProperties: druid.log.stmt.executableSql=true;druid.stat.mergeSql=false;druid.stat.slowSqlMillis=5000;config.decrypt=false;config.decrypt.key=${spring.datasource.druid.decrypt.publickey} # \u901A\u8FC7connectProperties\u5C5E\u6027\u6765\u6253\u5F00mergeSql\u529F\u80FD\uFF1B\u6162SQL\u8BB0\u5F55
      useGlobalDataSourceStat: false # \u5408\u5E76\u591A\u4E2ADruidDataSource\u7684\u76D1\u63A7\u6570\u636E
      # \u914D\u7F6E DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # IP \u767D\u540D\u5355\uFF0C\u6CA1\u6709\u914D\u7F6E\u6216\u8005\u4E3A\u7A7A\uFF0C\u5219\u5141\u8BB8\u6240\u6709\u8BBF\u95EE
        allow:  # 127.0.0.1,localhost
        # IP \u9ED1\u540D\u5355\uFF0C\u82E5\u767D\u540D\u5355\u4E5F\u5B58\u5728\uFF0C\u5219\u4F18\u5148\u4F7F\u7528
        deny: #192.168.31.253
        # \u7981\u7528 HTML \u4E2D Reset All \u6309\u94AE
        reset-enable: false
        # \u767B\u5F55\u7528\u6237\u540D/\u5BC6\u7801
        login-username: root
        login-password: bpdev
        # \u6162SQL\u8BB0\u5F55
      filter:
        stat:
          enabled: true
          # \u6162SQL\u8BB0\u5F55
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true



mybatis-plus:
  //mapper-locations: classpath:/mapper/${system-conf.dao}/*.xml
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    local-cache-scope: session
    map-underscore-to-camel-case: false
