server:
  servlet:
#    context-path: /springboot-jedis
  port: 8081

logging:
  level:
    cn.xiaocai: debug

spring:
  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: 121.4.26.45 # Redis服务器地址
    port: 9733 # Redis服务器连接端口
    password: Zhang@2020.cn
    timeout: 3000 # Redis连接超时时间
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接
