package cn.xiaocai.demo.kingbase.web.mapper.kingbase;

import cn.xiaocai.demo.kingbase.web.model.kingbase.KbAccount;
import java.util.List;

public interface KbAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Jun 28 15:56:44 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Jun 28 15:56:44 CST 2022
     */
    int insert(KbAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Jun 28 15:56:44 CST 2022
     */
    KbAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Jun 28 15:56:44 CST 2022
     */
    List<KbAccount> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Jun 28 15:56:44 CST 2022
     */
    int updateByPrimaryKey(KbAccount record);
}