package cn.xiaocai.demo.kingbase.web.mapper.kingbase;

import cn.xiaocai.demo.kingbase.web.model.kingbase.KbOrder;
import java.util.List;

public interface KbOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Tue Jun 28 15:56:44 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Tue Jun 28 15:56:44 CST 2022
     */
    int insert(KbOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Tue Jun 28 15:56:44 CST 2022
     */
    KbOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Tue Jun 28 15:56:44 CST 2022
     */
    List<KbOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Tue Jun 28 15:56:44 CST 2022
     */
    int updateByPrimaryKey(KbOrder record);
}