limit:
  repository:
    redis:
      cluster: false
      sentinel: false
      clusterUrl:
      sentinelUrl:
      masterName:
      hostName:
      port:
      password: 12345345
      maxTotal: 8
      maxIdle: 8
      minIdle: 2
      maxWaitMillis: -1
      blockWhenExhausted: true
      timeOut: 1000

