server:
  port: 8802
  servlet:
    context-path: /springboot-rabbitmq

spring:
  #配置rabbitMq 服务器
  rabbitmq:
    host: 192.168.10.127
    port: 5672
    username: bpdev
    password: 123456
    virtual-host: bpdev
    #消息确认配置项

    #确认消息已发送到交换机(Exchange)
    publisher-confirms: true   # publisher-confirm-type:correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true