package com.xiaocai.demo.mybatisplus.web.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.xiaocai.demo.mybatisplus.web.entity.Account;
import com.xiaocai.demo.mybatisplus.web.vo.AccountVo;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;

public interface AccountMapper extends BaseMapper<Account> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Mar 01 14:48:45 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Mar 01 14:48:45 CST 2022
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Mar 01 14:48:45 CST 2022
     */
    Account selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Mar 01 14:48:45 CST 2022
     */
    List<Account> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Mar 01 14:48:45 CST 2022
     */
    int updateByPrimaryKey(Account record);

    /**
     *  不写参数绑定注解  @Param
     * @param page
     * @param account
     * @return
     */
    Page<Account>  selectAllByPages(Page<Account> page, Account account);


    /**
     *  写参数绑定注解  @Param
     * @param page
     * @param account
     * @return
     */
    Page<Account>  selectAllWithParamsByPages(Page<Account> page, @Param("account")Account account);


    Account selectAccountById(Long id);


    /**
     * 不分页的写法
     *  写参数绑定注解  @Param
     * @param account
     * @return
     */
    List<Account>  selectAllWithParamsByNoPages(Page<Account> page, @Param("account")Account account);


    List<Account> selectAllByAccountPassList(@Param("pass") Long[] pass);

    List<Account> selectAllByAccountvoList(@Param("accountVo") AccountVo accountVo);

    List<Account> selectAllByAccountvoList2(@Param("accountVo") AccountVo accountVo);

    int updateBalanceDecimal(@Param("money") BigDecimal money, @Param("id") Long id);

    int updateBalanceString(@Param("money") String money, @Param("id") Long id);
}